openapi: 3.0.0
info:
  title: Virtual device API
  description: This is the OpenAPI specifications for the virtual device API
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Default test server
paths:
  /settings:
    summary: Update the general settings
    get:
      operationId: getSettings
      summary: Get the current settings
      tags:
        - Settings
      responses:
        200:
          description: The current settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'
    put:
      operationId: updateSettings
      summary: Update the settings
      tags:
        - Settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings'
      responses:
        204:
          description: Settings updated
  /users:
    summary: Update the allowed users
    get:
      operationId: getUsers
      summary: Get the list of users
      tags:
        - Users
      responses:
        200:
          description: An array of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersArray'
    post:
      operationId: createUser
      summary: Create a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: User created
    put:
      operationId: updateUser
      summary: Update an user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        204:
          description: User updated
    delete:
      operationId: deleteUser
      summary: Delete an user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: foo
              required:
                - username
      responses:
        204:
          description: User deleted
  /commands:
    summary: Update the device commands
    get:
      operationId: getCommands
      summary: Get the list of commands
      tags:
        - Commands
      responses:
        200:
          description: An array of commands
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandsArray'
    post:
      operationId: createCommand
      summary: Create a new command
      tags:
        - Commands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Command'
      responses:
        201:
          description: Command created
    put:
      operationId: updateCommand
      summary: Update a command
      tags:
        - Commands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Command'
      responses:
        204:
          description: Command updated
  /commands/{commandId}:
    delete:
      operationId: deleteCommand
      summary: Delete a command
      tags:
        - Commands
      parameters:
        - in: path
          name: commandId
          schema:
            type: string
            example: echo
          required: true
          description: Name of the command to delete
      responses:
        204:
          description: Command deleted
components:
  schemas:
    AuthType:
      type: string
      enum:
        - pass
        - pubkey
    Settings:
      type: object
      properties:
        general:
          type: object
          properties:
            port:
              type: integer
              minimum: 0
              maximum: 65535
              example: 22
            banner:
              type: string
            invalidCmdMsg:
              type: string
        prompt:
          type: object
          properties:
            default:
              type: string
              example: \u@\h\$
            continuation:
              type: string
              example: '>'
            selection:
              type: string
              example: '#?'
            lines:
              type: string
              example: +
    User:
      type: object
      properties:
        username:
          type: string
          example: foo
        authtype:
          $ref: '#/components/schemas/AuthType'
          example: pass
        password:
          type: string
          example: bar
        key:
          type: string
          example: null
      required:
        - username
    Command:
      type: object
      properties:
        name:
          type: string
        content:
          type: string
      required:
        - name
        - content
    UsersArray:
      type: array
      items:
        $ref: '#/components/schemas/User'
    CommandsArray:
      type: array
      items:
        $ref: '#/components/schemas/Command'
